#configfile config.yaml
inputfiles: ~/Desktop/Uploaded_files/demofiles_wetsus4000/
silvadatabase:  -db ~/Desktop/Uploaded_files/humann_dbs/rRNA_SILVA128/
trimmomatic:  --trimmomatic ~/Desktop/kneaddataMap/Trimmomatic-0.36/
--bypass-trf: --bypass-trf
fastqc-start: --run-fastqc-start
fastqc-end:  --run-fastqc-end