#configfile config.yaml
#dataset:
#  first: first,
#  second : second
#samples:
#  A : R1
#  B : R2

inputfiles:


# kneaddata
silvadatabase:
trimmomatic:
bypass_trf:
fastqc_start:
fastqc_end:

name: name_map
samples: [_R1 ,_R2]
dataset : []

# humanntool

bypass_n_search:
remove-temp-output:
verbose:
protein_db:
nucleotide_db:

interleave_map:






