#configfile config.yaml
#dataset:
#  first: first,
#  second : second
#samples:
#  A : R1
#  B : R2

inputfiles: /Users/bengels/Desktop/Uploaded_files/poging2_v1/
silvadatabase:  -db ~/Desktop/Uploaded_files/humann_dbs/silvadb/
trimmomatic:  --trimmomatic ~/Desktop/kneaddataMap/Trimmomatic-0.36/
--bypass-trf: --bypass-trf
fastqc-start: --run-fastqc-start
fastqc-end:  --run-fastqc-end
name: map_name
samples: [_R1 ,_R2]
dataset : [demofile_wetsus_0, demofile_wetsus_1]

# humanntool

bypass-n-search: --bypass-nucleotide-search
remove-temp-output: --remove-temp-output
verbose: --verbose
protein-db: --protein-database ~/Desktop/Uploaded_files/humann_dbs/unireffull/
nucleotide_db: --nucleotide-database /Users/bengels/Desktop/Uploaded_files/humann_dbs/chocophlan

interleave_map: /Users/bengels/Desktop/StageWetsus2022/SnakePipeMultiHumaNn/interleave_map/

