#configfile config.yaml
#dataset:
#  first: first,
#  second : second
#samples:
#  A : R1
#  B : R2

inputfiles:


# kneaddata
silvadatabase:
trimmomatic:
bypass_trf:
fastqc_start:
fastqc_end:
name:
samples: [_R1 ,_R2]
dataset : []

tsv_samples: [genefamilies, pathabundance, pathcoverage]

# humanntool

bypass_n_search:
remove_temp_output:
verbose:
protein_db:
nucleotide_db:

interleave_map:

#user data
user_index:
research_index:




